default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: doryoku
  password: manager
  host: localhost
  pool: 5

development:
  <<: *default
  database: progress_dev

test:
  <<: *default
  database: progress_test

production:
  <<: *default
  database: progress_prod
