# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password:
  host: localhost
  pool: 5

development:
  <<: *default
  database: progress_dev

test:
  <<: *default
  database: progress_test

production:
  <<: *default
  database: progress_prod
